import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Menu extends JFrame {
    private JPanel contentPane;
    private JButton btnStartGame;
    private JLabel lblTitle;

    public Menu() {
        setTitle("Flappy Bird Menu");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(100, 100, 400, 300);
        setLocationRelativeTo(null);

        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout());
        setContentPane(contentPane);

        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 50));
        contentPane.add(centerPanel, BorderLayout.CENTER);

        lblTitle = new JLabel("Flappy Bird");
        lblTitle.setFont(new Font("Arial", Font.BOLD, 36));
        centerPanel.add(lblTitle);

        btnStartGame = new JButton("Start Game");
        btnStartGame.setFont(new Font("Arial", Font.PLAIN, 18));
        btnStartGame.setPreferredSize(new Dimension(150, 50));
        btnStartGame.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close the menu
                App.startGame(); // Start the game
            }
        });

        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
        buttonPanel.add(btnStartGame);
        contentPane.add(buttonPanel, BorderLayout.SOUTH);

        // This generated code would be created when compiling with IntelliJ
        $$$setupUI$$$();
    }

    // This is a placeholder for the method that would be generated by IntelliJ
    private void $$$setupUI$$$() {
        // This would be filled in automatically by IntelliJ
    }
}